# Generated by Django 4.2.5 on 2023-09-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Api",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=60)),
                ("about", models.CharField(max_length=260)),
                ("added_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
